AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Microservice that scrapes the web for Covid bed data

Globals:
  Function:
    Timeout: 900
    CodeUri: app/
    Runtime: python3.8
    Environment:
      Variables:
        INDIA_COVID_SKIP_UPLOADING: ""
        INDIA_COVID_AUTH_HEADER: !Ref HeaderAuth
        INDIA_COVID_HOST: !Ref CovidHost

Parameters:
  HeaderAuth:
    Type: String
    Default: raJ@xTJqBkjqLKJ0AOCQR#q
  CovidHost:
    Type: String
    Default: iitk-covid-help-1109904003.ap-south-1.elb.amazonaws.com

Resources:
  DataScraper:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-DataScraper"
      Handler: lambda_function.lambda_handler
      Policies:
        - AWSLambdaExecute
      Events:
        Delhi30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: false
            Input: "{\"state\": \"Delhi\", \"city\": \"Delhi\"}"
        AP30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Andhra Pradesh\"}"
        Bihar30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Bihar\"}"
        GujaratAhmedabad30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Gujarat\", \"city\": \"Ahmedabad\"}"
        GujaratGandhinagar30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Gujarat\", \"city\": \"Gandhinagar\"}"
        GujaratSurat30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Gujarat\", \"city\": \"Surat\"}"
        GujaratVadodara30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Gujarat\", \"city\": \"Vadodara\"}"
        Haryana30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Haryana\"}"
        JharkhandRanchi30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Jharkhand\", \"city\": \"Ranchi\"}"
        KABangalore30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Karnataka\", \"city\": \"Bengaluru\"}"
        Kerala30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Kerala\"}"
        MHNaviMumbai30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Maharashtra\", \"city\": \"Navi Mumbai\"}"
        MHPanvel30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Maharashtra\", \"city\": \"Panvel\"}"
        MHPune30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Maharashtra\", \"city\": \"Pune\"}"
        MHThane30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Maharashtra\", \"city\": \"Thane\"}"
        MHNashik30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Maharashtra\", \"city\": \"Nashik\"}"
        MHBeed30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Maharashtra\", \"city\": \"Beed\"}"
        MP30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Madhya Pradesh\"}"
        Puducherry30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Puducherry\"}"
        PunjabLudhiana30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Punjab\", \"city\": \"Ludhiana\"}"
        Rajasthan30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Rajasthan\"}"
        Telangana30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Telangana\"}"
        TN30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Tamil Nadu\"}"
        Uttarakhand30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Uttarakhand\"}"
        UP30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"Uttar Pradesh\"}"
        WB30:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
            Input: "{\"state\": \"West Bengal\"}"
        ImplicitApi:
          Type: Api
          Properties:
            Path: /scraper
            Method: POST
            RestApiId:
              Ref: ApiGateway

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: India Covid Scraper API Gateway
      StageName: v0
      EndpointConfiguration: 'PRIVATE'
      Auth:
        ResourcePolicy:
          CustomStatements: [ {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "execute-api:Invoke",
            "Resource": "execute-api:/*"
          } ]
